-- Generated by cloud/scripts/build-eligibility-seed.mjs from the rules
-- hand-decoded in cloud/scripts/lib/eligibility-rules-data.mjs (source:
-- vaccine-add-new.mxe's 24+ age/eligibility CASE blocks). Re-run
-- `npm run seed:eligibility` after editing that file.
--
-- 28 rules. Each INSERT is a select-by-short_code
-- join against the vaccine table (see supabase/seed/vaccines.sql) — a
-- rule whose short_code isn't in the current formulary inserts zero rows
-- rather than failing. See eligibility-rules-data.mjs for the two CASE
-- blocks deliberately NOT seeded here (medicarehomevisit, DEFAULT CASE)
-- and every short_code-mapping judgment call.

delete from eligibility_rule
where vaccine_id in (select id from vaccine where short_code in ('spikevax12', 'mnexspike', 'spikevax311', 'spikevax6mo11', 'comirnaty12', 'pfizer342425', 'flucelvaxpfs', 'afluriamdv', 'fluad', 'arexvy', 'shingrix1', 'shingrix2', 'engerix1', 'engerix2', 'engerix3', 'prevnar20', 'boostrix', 'gardasil1', 'gardasil2', 'gardasil3', 'menveo', 'vaqtaadult1', 'vaqtaadult2', 'typhim', 'mmr1', 'mmr2', 'priorix1', 'priorix2'));

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 12, null, null, false, 0
from vaccine where short_code = 'spikevax12';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 12, null, 'Age gate inherited from the retired ''spikevax12'' macro code (mNEXSPIKE reads as its 2025-26 successor product) — verify against the current package insert, not re-derived from scratch.', false, 0
from vaccine where short_code = 'mnexspike';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 3, 11, null, false, 0
from vaccine where short_code = 'spikevax311';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, null, null, 'Old macro''s closest equivalent (''spikevax311'') gated ages 3-11; this formulary item is labeled 6mo-11, a wider band. Age range intentionally left unset — verify against the current package insert before enforcing a numeric gate.', false, 0
from vaccine where short_code = 'spikevax6mo11';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 12, null, null, false, 0
from vaccine where short_code = 'comirnaty12';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 3, 4, null, false, 0
from vaccine where short_code = 'pfizer342425';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 3, null, 'Fluad is the preferred vaccine for ages 65+. Confirm before entering a regular flu shot for a patient 65 or older.', false, 0
from vaccine where short_code = 'flucelvaxpfs';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 3, null, 'Fluad is the preferred vaccine for ages 65+. Confirm before entering a regular flu shot for a patient 65 or older.', false, 0
from vaccine where short_code = 'afluriamdv';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 18, null, 'Ages 18-64 require a documented solid organ transplant; 65+ has no additional requirement.', false, 0
from vaccine where short_code = 'fluad';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 60, null, 'Ages 60-74 require documented high-risk criteria per the macro''s own prompt (which literally read ''60-75'' — verify the exact upper bound against current ACIP guidance before relying on it).', false, 0
from vaccine where short_code = 'arexvy';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 50, null, null, false, 0
from vaccine where short_code = 'shingrix1';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 50, null, null, false, 0
from vaccine where short_code = 'shingrix2';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 20, null, null, false, 0
from vaccine where short_code = 'engerix1';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 20, null, null, false, 0
from vaccine where short_code = 'engerix2';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 20, null, null, false, 0
from vaccine where short_code = 'engerix3';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 19, null, 'Ages 19-49 require documented high-risk criteria; 50+ has no additional requirement.', false, 0
from vaccine where short_code = 'prevnar20';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 10, null, null, false, 0
from vaccine where short_code = 'boostrix';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 9, 45, null, false, 0
from vaccine where short_code = 'gardasil1';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 9, 45, null, false, 0
from vaccine where short_code = 'gardasil2';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 9, 45, null, false, 0
from vaccine where short_code = 'gardasil3';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 3, 55, null, false, 0
from vaccine where short_code = 'menveo';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 19, null, null, false, 0
from vaccine where short_code = 'vaqtaadult1';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 19, null, null, false, 0
from vaccine where short_code = 'vaqtaadult2';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 3, null, null, false, 0
from vaccine where short_code = 'typhim';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 3, null, null, true, 0
from vaccine where short_code = 'mmr1';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 3, null, null, true, 0
from vaccine where short_code = 'mmr2';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 3, null, null, true, 0
from vaccine where short_code = 'priorix1';

insert into eligibility_rule (vaccine_id, min_age, max_age, condition_note, pregnancy_warning, priority)
select id, 3, null, null, true, 0
from vaccine where short_code = 'priorix2';
