-- Generated by cloud/scripts/parse-formulary.mjs from the pharmacy's
-- v-macro-codes.xlsx "Macro codes" sheet — public drug/pricing data, safe
-- to commit. Do NOT commit the source .xlsx itself. Re-run
-- `npm run seed:formulary -- /path/to/v-macro-codes.xlsx` any time the
-- formulary changes; this file is regenerated in full each time.
--
-- 31 distinct vaccines (deduped by short_code, cross-checked
-- against ndc+name — see cloud/scripts/lib/formulary-parser.mjs).

insert into vaccine (name, ndc, dose, short_code, cash_price_cents, active)
values
  ('Abrysvo', '00069-0344-01', '1', 'abrysvo', 31199, true),
  ('Afluria MDV', null, '1', 'afluriamdv', null, true),
  ('Afluria PFS', null, '1', 'afluriapfs', null, true),
  ('Arexvy', '58160-0848-11', '1', 'arexvy', 31199, true),
  ('Boostrix', '58160-0842-52', '1', 'boostrix', 7199, true),
  ('Capvaxive', null, '1', 'capvaxive', 32589, true),
  ('Comirnaty 2025-26 12+', '00069-2528-10', '1', 'comirnaty12', 14799, true),
  ('Engerix 20 (age 20+)', '58160-0821-52', '1', 'engerix1', 9299, true),
  ('Engerix 20 (age 20+)', '58160-0821-52', '2', 'engerix2', 9299, true),
  ('Engerix 20 (age 20+)', '58160-0821-52', '3', 'engerix3', 9299, true),
  ('Fluad', '70461-0123-03', '1', 'fluad', 8499, true),
  ('Flucelvax MDV', '70461-0323-03', '1', 'flucelvaxmdv', 4299, true),
  ('Flucelvax PFS', null, '1', 'flucelvaxpfs', null, true),
  ('FluMist (age 2-49)', null, '1', 'flumist', null, true),
  ('Fluzone HD', null, '1', 'fluzonehd', null, true),
  ('Gardasil', '00006-4121-02', '1', 'gardasil1', 31299, true),
  ('Gardasil', '00006-4121-02', '2', 'gardasil2', 31299, true),
  ('Gardasil', '00006-4121-02', '3', 'gardasil3', 31299, true),
  ('Menveo', '58160-0955-09', '1', 'menveo', 17999, true),
  ('MMR-II', '00006-4681-00', '1', 'mmr1', 11999, true),
  ('MMR-II', '00006-4681-00', '2', 'mmr2', 11999, true),
  ('mNEXSPIKE', null, '1', 'mnexspike', null, true),
  ('Prevnar 20', '00005-2000-10, 00005-2000-02', '1', 'prevnar20', 27999, true),
  ('Priorix', null, '1', 'priorix1', 11999, true),
  ('Priorix', null, '2', 'priorix2', 11999, true),
  ('Shingrix', '58160-0823-11', '1', 'shingrix1', 23299, true),
  ('Shingrix', '58160-0823-11', '2', 'shingrix2', 23299, true),
  ('Spikevax', null, '1', 'spikevax6mo11', null, true),
  ('Typhim Vi', '49281-0790-51', '1', 'typhim', 17999, true),
  ('Vaqta adult', '00006-4096-02', '1', 'vaqtaadult1', 9799, true),
  ('Vaqta adult', null, '2', 'vaqtaadult2', null, true)
on conflict (short_code) do update set
  name = excluded.name,
  ndc = excluded.ndc,
  dose = excluded.dose,
  cash_price_cents = excluded.cash_price_cents,
  active = true,
  updated_at = now();
